### ISSUE TITLE
Enforce single variable declarations on a new line

### ISSUE THREAD

**Issue by jamespamplin** [jamespamplin/eslint-config-idiomatic#2]
``` js
// Expect error:
var foo = "bar", num = 1;

// Good:
var foo = "bar",
  num = 1,
  undef;
```

**Comment by jamespamplin** [comment]
Rule not yet implemented, see: eslint/eslint#1622

**Comment by demrks** [comment]
@jamespamplin It is now: http://eslint.org/docs/2.0.0/rules/one-var-declaration-per-line.html

**Comment by jamespamplin** [comment]
Thanks again @demrks - will put this in the next release including ESLint 2.0 support.
