### ISSUE TITLE
`space-in-parens` exceptions

### ISSUE THREAD

**Issue by demrks** [jamespamplin/eslint-config-idiomatic#4]
You are currently using `"space-in-parens": [2, "always"]`, which enforces spaces inside all parens. Since [idomatic.js](https://github.com/rwaldron/idiomatic.js/) has some exceptions, you should probably consider adding some of these too:

```
// 2.C.1.1
// Functions with callbacks
foo(function() {
  // Note there is no extra space between the first paren
  // of the executing function call and the word "function"
});

// Function accepting an array, no space
foo([ "alpha", "beta" ]);

// 2.C.1.2
// Function accepting an object, no space
foo({
  a: "alpha",
  b: "beta"
});

// Single argument string literal, no space
foo("bar");

// Inner grouping parens, no space
if ( !("foo" in obj) ) {

}
```

I already asked [eslint](https://github.com/eslint/eslint) if they could add support for _single argument string literal_, _functions with callbacks_ and _inner grouping parens_. But _function accepting an object_ and _function accepting an array_ is already possible, see https://github.com/eslint/eslint/blob/master/docs/rules/space-in-parens.md:

`"space-in-parens": [2, "always", { "exceptions": ["{}", "[]", "()", "empty"] }]`

**Comment by jamespamplin** [comment]
Thanks for this @demrks, this rule does annoy me at times when writing code. Not sure if the `exceptions` will cover all cases correctly, but will write some tests to check.

**Comment by demrks** [comment]
@jamespamplin  It doesn't unfortunately, but it's slightly better than without `exceptions` IMO. At least you are allowed to write something like `foo([ "alpha", "beta" ]);` (2.C.1.1).

You'd have to write `elements.push( matches[ idx ]);` instead of`elements.push( matches[ idx ] );` (6.A.2.1) though. Not great, but ok-ish, I guess.
